name: Build makemogg library

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install build tools (Linux/macOS)
              if: runner.os != 'Windows'
              run: |
                  sudo apt-get update || true
                  sudo apt-get install -y build-essential || true

            - name: Install build tools (Windows)
              if: runner.os == 'Windows'
              run: |
                  choco install make mingw -y

            - name: Build makemogg library
              run: |
                  make

            - name: Find libwinpthread-1.dll (Windows)
              if: runner.os == 'Windows'
              run: |
                  where libwinpthread-1.dll || dir /s /b libwinpthread-1.dll > found.txt || echo not found
                  for /f %%i in ('dir /s /b libwinpthread-1.dll') do copy \"%%i\" .

            - name: Upload makemogg library and libwinpthread-1.dll
              uses: actions/upload-artifact@v4
              with:
                  name: makemogg-lib-${{ runner.os }}
                  path: |
                      makemogg.dll
                      libwinpthread-1.dll
                      libmakemogg.so
                      libmakemogg.dylib
