name: Build makemogg library

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install build tools (Linux/macOS)
              if: runner.os != 'Windows'
              run: |
                  sudo apt-get update || true
                  sudo apt-get install -y build-essential || true

            - name: Install build tools (Windows)
              if: runner.os == 'Windows'
              run: |
                  choco install make mingw -y

            - name: Download MinGW-w64 (win32 threads)
              if: runner.os == 'Windows'
              run: |
                  curl -L -o mingw.zip https://github.com/brechtsanders/winlibs_mingw/releases/download/14.2.0-17.0.6-11.0.1-ucrt-r5/winlibs-x86_64-posix-seh-gcc-14.2.0-mingw-w64ucrt-11.0.1-r5.7z
                  7z x mingw.zip -omyg_mingw
                  echo "$PWD/my_mingw/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

            - name: Build makemogg library
              run: |
                  make

            - name: Upload makemogg library
              uses: actions/upload-artifact@v4
              with:
                  name: makemogg-lib-${{ runner.os }}
                  path: |
                      makemogg.dll
                      libmakemogg.so
                      libmakemogg.dylib
                                makemogg
                                makemogg.exe
